title: Ruby Best Practices
domain: blog.rubybestpractices.com
description: Increase your productivity -- Write Better Code
authors:
  gregory: Gregory Brown
  JEG2: James Edward Gray II
  jia: Jia Wu
