title: Ruby Best Practices
domain: blog.rubybestpractices.com
description: Increase your productivity -- Write Better Code
authors:
  gregory: 
    name: Gregory Brown
    email: gregory.t.brown@gmail.com
  jamesbritt: 
    name: James Britt
    email: james.britt@gmail.com
  rklemme: 
    name: Robert Klemme
    email: shortcutter@gmail.com
